services:
  payload:
    image: cms:latest
    container_name: cms
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - csclub
    extra_hosts:
      - "auth.csclub.org.au:host-gateway"

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    image: mongo:latest@sha256:e0ce8c35124d4a9f9785532d1f268f39e9728ffa1cb38f46fa482436424c4bd3
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - csclub

volumes:
  data:

networks:
  csclub:
    external: true
